### ISSUE TITLE
Import event feeds doesn't assign the organization after import

### ISSUE THREAD

**Issue by alex0107** [kartevonmorgen/wp-kvm-syndication-toolbox#16] opened 2024-05-26 08:46 UTC
A organisator from a organization creates a import and the events don't have the right location or organisator and the events is not displayed...

**Comment by alex0107** [comment] 2024-05-26 08:48
<img width="512" alt="image" src="https://github.com/kartevonmorgen/wp-kvm-syndication-toolbox/assets/17063865/33b5a8f9-1007-4809-a9f7-73252262de96">

Maybe this is the problem? The default organisation is the first entry and not "no" entry. The Kooperationspartner is always the first one...

**Comment by wellemut** [comment] 2024-06-06 19:23
@alex0107 For me the problem description seems not sufficient, but maybe @sjoerdtakken can help already...

**Comment by sjoerdtakken** [comment] 2024-06-09 20:28
On a Organisation Detail Page in Wordpress the Events of the Organisation are shown. If on a event from another organisation the kooperationspartner is fillled, the the event will also be shown on the Organsition Detail Page of the Kooperationspartner. 
Importing events has no influence on was is set with the kooperationspartner.
I do not really understand what the Problem ist. Please show me a case and then I can say something about it.

**Comment by sjoerdtakken** [comment] 2024-06-16 08:40
This Problem was by bne-marburg.de

An User of an Organisation has most often the Role "Author".

In the Events Manager standard an Author is not allowed to publish events.

We can change that in the Settings ot the Events Manager, see the screenshot attached
![EventsManagerSettingsAuthorPublishEvents](https://github.com/kartevonmorgen/wp-kvm-syndication-toolbox/assets/36988889/da0063bd-d9ca-473e-b083-ead92b148eee)

Also make sure that the location is available in the ICal Feed. It is not enough that the location is mentioned in the description. It should be known as an Location Field in the ICal Feed. Only then the location can be found und become a Pointer on the Map of Tommorow

**Comment by sjoerdtakken** [comment] 2024-06-16 08:41
its fixed so we close it

**Closed as completed by sjoerdtakken** 2024-06-16 08:41 UTC
Labels: bug
